<a href="https://colab.research.google.com/github/inthyes/python-base/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모듈과 패키지

In [ ]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일(.py)
# 패키지는 여러 모듈을 묶은 것(폴더)
# import 모듈

# 모듈.변수
# 모듈.함수()

In [ ]:
import math
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [ ]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import * # *이 all이라는 뜻
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [ ]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [ ]:
import numpy as np # numpy는 라이브러리(패키지와 모듈을 모아놓음, numpy -> numerical python)
a = np.array([1, 2, 3])
print(a)
type(np.array)

[1 2 3]


builtin_function_or_method

In [ ]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[ 0.39813012 -1.18162731  0.93799181]
 [ 1.63947639  1.05740095  0.29354003]
 [-0.68502748  0.45711845 -0.27034697]]


In [ ]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 0.71922391  0.90522824 -1.27465487]
 [-1.42388762  0.52467795 -1.27987263]
 [-0.43187253 -1.05862509  1.42606823]]


In [ ]:
from numpy.random import randn
print(randn(3,3))

[[ 0.6742058   0.57855104  0.7203988 ]
 [ 0.78833041 -0.01776284  0.4007551 ]
 [-0.48070109  0.37157822 -0.35617926]]


In [ ]:
from numpy.random import *
print(rand(3,3)) # uniform distribution

[[0.43018122 0.77297766 0.64372734]
 [0.84757166 0.39029554 0.23875279]
 [0.10506096 0.07002546 0.49784219]]


In [ ]:
from numpy.random import randn as rn
print(rn(3,3))

[[ 0.36629623 -1.69430813  0.30866472]
 [-0.53014823  0.48966962  0.66819978]
 [-0.49098354  0.13460608  0.33867542]]


In [23]:
from numpy.random import rand as rn, randn as r
print(rn(3,3))
print(r(3,3))

[[0.32584249 0.73982553 0.99927685]
 [0.72861791 0.25604463 0.49066603]
 [0.63319838 0.26802427 0.04135827]]
[[-0.89838467 -0.16695776  0.30235301]
 [-0.97542282 -1.38945202  1.58373112]
 [-0.71149649  1.71580892  0.41992686]]


numpy 본격적으로

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4]) # list가 입력으로 들어가는 함수
print(a, type(a))
print(a.dtype) # data type
print(a.shape) # 많이 쓰임

b = np.array([1, 2, 3.1, 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로 바뀜

[1 2 3 4] <class 'numpy.ndarray'>
int64
(4,)
float64


In [ ]:
a = np.array(2**600) # 오버플로우 안 남.
b = np.array(2**63-1)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

4149515568880992958512407863691161151012446232242436899995657329690652811412908146399707048947103794288197886611300789182395151075411775307886874834113963687061181803401509523685376
object
9223372036854775807
int64


In [ ]:
A = np.array([[1,2],[3,4]]) # 이 셀부터는 import numpy as np는 실행했다는 전제로 진행
# A = np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함

print(A)
print(A.shape)
print(A.ndim) # 차원은 담겨있다는 개념으로 이해할 것
print(A.size) # 전체 성분의 수 A.shape[0] * A.shape[1] * ... * A.shape(n)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A)) # A의 사이즈에 맞게 0으로 삽입하여 출력
print(np.ones(5))
print(np.zeros([3,3])) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안됨

import torch
print(torch.zeros(3,3))

print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint = False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c) # 벡터의 합 출력

[5 7 9]


In [ ]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A + B
D = A - B
print(C)
print(D)
print()
print(A * B) # 성분끼리의 곱 (Hadamard product)
print(A / B) # 나누기도 마찬가지
print(B**2) #제곱도 각 성분에 대해서 해준다
# [[1,2,3],[1,2,3]] + [[4,5,6],[1,1,1]]

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A*B)
print(A@B)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


numpy의 인덱싱과 슬라이싱

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1, 2, 3,],[4, 5, 6],[7, 8, 9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # numpy에서만 지원하는 문법
print(A[1,:]) # 1행, 전부
print(A[1, 0:3:2]) # 0:3:2는 열에 대한 것
print(A[:,2]) #전부, 2열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[4 5 6]
[4 6]
[3 6 9]


In [ ]:
# boolean 인덱싱
a = [1, 2, 3, 4, 5, 3, 3]
print(a == 3) # 여러개값이 들어있는 리스트와 숫자 3이 같느냐. 다름.
A = np.array([[1, 2, 3, 4], [5, 3, 7, 3]])
print(A == 3) # 각 요소에 대해 비교해줌
print(A[A == 3]) # True, False가 담긴 행렬로 인덱싱 가능

A[A == 3] = 100 # 주소까지 물고와서 값을 변경 (3인 애들ㅇ르 100으로 바꿔줘)
print(A)

A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([True, False, False, True]) #리스트에서도 사용 가능

A[B, :] # 0행, 3행 슬라이싱

b = np.array([1, 2, 3, 4])
print(b)
print(b[[True, True, False, False]])
c = [1, 2, 3, 4]
c[[True, True, False, False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 2]


In [ ]:
# 3차원 행렬 인덱싱
A = np.array([[[0, 1, 2, 3], [4, 5, 6, 7],[8, 9, 10, 11]],
             [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])

print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽 shape값이 하나 추가
print(A[0, 1, 2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


numpy의 여러 함수들

In [ ]:
A = np.random.randn(3, 3) # 튜플로 안줘도 됨
B = np.random.rand(3, 3)
print(A)
print(B)
print(A[:,0]<0,)
print(A[A[:,0]<0, :]) # 0번째 열의 성분이 음수인 행

[[ 1.27720054  0.82021447  0.82251542]
 [-0.96100121  0.32859793 -1.66124233]
 [-1.25653622 -1.05778912  0.54207319]]
[[0.83431575 0.86096602 0.51720666]
 [0.6529426  0.51761706 0.36332674]
 [0.37702245 0.14737951 0.04100042]]
[False  True  True]
[[-0.96100121  0.32859793 -1.66124233]
 [-1.25653622 -1.05778912  0.54207319]]


In [ ]:
A = np.random.randn(3, 3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A,2)) # 소수점 둘째자리까지 반올림
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[-0.71935685 -2.14782247 -0.96158774]
 [ 0.87509416 -0.30329944 -0.24470454]
 [-0.1268632   0.75609309  0.69324627]]
[[0.71935685 2.14782247 0.96158774]
 [0.87509416 0.30329944 0.24470454]
 [0.1268632  0.75609309 0.69324627]]
[[0.84814907 1.46554511 0.9806058 ]
 [0.93546467 0.55072629 0.4946762 ]
 [0.3561786  0.86953613 0.83261412]]
[[0.48706541 0.11673808 0.38228544]
 [2.39910118 0.73837796 0.78293583]
 [0.88085417 2.12993846 2.00019819]]
[[-0.32939773  0.76445452 -0.03916947]
 [-0.13342379 -1.19303471 -1.40770375]
 [-2.06464597 -0.27959078 -0.36636997]]
1.0
1.0
1.0
[[-0.72 -2.15 -0.96]
 [ 0.88 -0.3  -0.24]
 [-0.13  0.76  0.69]]


In [ ]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [ ]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1, 2, np.nan, 3, 4]))
print(np.isinf([1, 2, 3, 4, np.inf]))

[False False  True False False]
[False False False False  True]


In [ ]:
A = np.random.randn(3, 4)
print(A)
print(np.max(A))
print(np.max(A, axis = 0)) # 행을 기준으로 3개 중에서 고름
print(np.max(A, axis = 1)) # 열을 기준으로 (4개로)

print(np.max(A, axis = 0, keepdims = True)) # 3행 1열
print(np.max(A, axis = 1, keepdims = True)) # 1행 4열
print(np.min(A))
print(np.min(A, axis = 0))

print(np.argmax(A)) # 가장 큰 값의 인덱스값 출력
print(np.argmax(A, axis = 0)) # 각각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A, axis = 1)) # 각각 행에서 가장 큰 애가 존재하는 인덱스

SyntaxError: ignored

In [ ]:
a = np.random.randn(6, 1)
print(a)
a_sorted = np.sort(a, axis = 0) # axis 안주면 가로로 정렬하는게 기본이라 정렬이 잘 안됨
print(a_sorted)
print(np.flipud(a_sorted)) # 내림차순

[[ 1.28582625]
 [ 1.67308643]
 [-2.04226981]
 [-1.65935626]
 [ 0.90225207]
 [ 0.77086351]]
[[-2.04226981]
 [-1.65935626]
 [ 0.77086351]
 [ 0.90225207]
 [ 1.28582625]
 [ 1.67308643]]
[[ 1.67308643]
 [ 1.28582625]
 [ 0.90225207]
 [ 0.77086351]
 [-1.65935626]
 [-2.04226981]]


In [ ]:
A = np.random.randn(3, 4)
print(A)
print(np.sum(A))
print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1, keepdims = True)) # 3행 1열짜리 2D array
print(np.mean(A))
print(np.mean(A, axis = 1))
print(np.mean(A, axis = 1, keepdims = True))
print(np.std(A)) # standard deviation 표준편차

[[ 0.02186597  0.48869393  0.7989499   0.0439027 ]
 [-0.24939575 -0.97887747 -0.70791968 -0.05777605]
 [ 0.04897935  1.15031163  1.33641891  1.60607192]]
3.501225360398335
[ 1.3534125  -1.99396895  4.14178181]
[[ 1.3534125 ]
 [-1.99396895]
 [ 4.14178181]]
0.29176878003319456
[ 0.33835313 -0.49849224  1.03544545]
[[ 0.33835313]
 [-0.49849224]
 [ 1.03544545]]
0.7677882747879778


In [ ]:
A = np.random.randint(1, 5, size = (12,)) # 1부터 5까지 랜덤한 int로 12개 (12, 1), (12, 1, 1) 로 사용 가능
print(A)
print(A.shape)

B = A.reshape(2, 2, 3) # (x, y, z) : z개씩 y묶음으로 묶여진 게 x개.(y, z)개의 행렬이 x묶음
print(B)
print(B.ndim) # 3차원 행렬

[2 4 2 2 2 1 3 1 4 3 2 2]
(12,)
[[[2 4 2]
  [2 2 1]]

 [[3 1 4]
  [3 2 2]]]
3


In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 1])

# print(a@b) # 사용은 가능하지만, 내적을 구할 때엔 형태가 맞아야 함

print(sum(a*b))

# 열벡터로 변경 후 사용
a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A = np.random.randn(4, 3, 2)
print(A.transpose(0, 1, 2).shape)
print(A.transpose(2, 1, 0).shape)

9
[[1]
 [2]
 [3]]
[[9]]
[[9]]
(4, 3, 2)
(2, 3, 4)


In [ ]:
A = np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라 (-1 사용)
print(A.reshape(2, 5, -1).shape)

print(A.reshape(1, -1).shape) # 2차원 행 벡터
print(A.reshape(-1, 1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(1, 20)
(20, 1)


In [ ]:
x = np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, ...] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,...,3,:].shape)

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)


In [ ]:
A = np.ones((2, 2))
B = np.zeros((2, 2))
C = np.hstack([A, B])
D = np.vstack([A, B])
E = np.block([A, B])
F = np.block([B, A])
G = np.block([[[A]],[[B]]]) # (2, 2, 2)
print(C)
print(D)
print(E)
print(F)
print(G, G.shape)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]] (2, 2, 2)


In [ ]:
A = np.random.randn(1, 1, 1, 3, 1, 1, 4, 1)
print(A)

print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis = (0, 2, 4, 5)).shape)

[[[[[[[[ 1.54610907]
       [ 0.99136876]
       [-0.3856635 ]
       [-1.34074111]]]]



    [[[[-1.90556206]
       [-1.52093485]
       [-0.55231767]
       [ 1.0126385 ]]]]



    [[[[ 1.35330156]
       [ 0.53216366]
       [-0.92949226]
       [ 0.0287752 ]]]]]]]]
(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [ ]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,:,:] # np.newaxis is None <- True
print(A1.shape) # 1이 추가, 열이 추가돼고 np.newaxix, 3, 4로 진행되는 것임
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)

A1 = np.expand_dims(A, axis = 0)
print(A1.shape)
A2 = np.expand_dims(A, axis = 2)
print(A2.shape)
A3 = np.expand_dims(A, axis = 1)
print(A3.shape)

A1 = A.reshape(1, 3, 4)
print(A1.shape)
A2 = A.reshape(3, 4, 1)
print(A2.shape)
A3 = A.reshape(3, 1, 4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)


In [ ]:
np.newaxis is None

True