<a href="https://colab.research.google.com/github/inthyes/ML-Study/blob/main/DeeplearningPytorchTextbook/2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], device = 'cuda:0'))
print(torch.tensor([[1,2],[3,4]], dtype = torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
temp = torch.tensor([[1, 2,], [3, 4]])
print(temp.numpy())

# GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환
temp = torch.tensor([[1, 2,], [3, 4]], device = "cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [3]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print("--------------------------")
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
--------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [4]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [5]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.shape)
print("--------------------------")
print(temp.view(4, 1))
print("--------------------------")
print(temp.view(-1))
print("--------------------------")
print(temp.view(1, -1))
print("--------------------------")
print(temp.view(-1, 1))

torch.Size([2, 2])
--------------------------
tensor([[1],
        [2],
        [3],
        [4]])
--------------------------
tensor([1, 2, 3, 4])
--------------------------
tensor([[1, 2, 3, 4]])
--------------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [6]:
import pandas as pd
data = pd.read_csv('/content/sample_data/mnist_test.csv')

In [7]:
x = torch.from_numpy(data['0'].values).unsqueeze(dim=1).float()
y = torch.from_numpy(data['1'].values).unsqueeze(dim=1).float()

In [8]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
  def __init__(self, csv_file):
    self.label = pd.read_csv(csv_file)
  def __len__(self):
    return len(self.label)

  def __getitem__(self, idx):
    sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
    label = torch.tensor(self.label.iloc[idx,3]).int()
    return sample, label

tensor_dataset = CustomDataset('/content/sample_data/mnist_test.csv')
dataset = DataLoader(tensor_dataset, batch_Size = 5, shuffle = True)

TypeError: DataLoader.__init__() got an unexpected keyword argument 'batch_Size'

In [9]:
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])

from torchvision.datasets import MNIST
import requests
download_root = '../data/MNIST_DATASET'

train_dataset = MNIST(download_root, transform = mnist_transform, train = True, download = True)
valid_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)
test_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)

100%|██████████| 9912422/9912422 [00:00<00:00, 102418617.68it/s]


Extracting ../data/MNIST_DATASET/MNIST/raw/train-images-idx3-ubyte.gz to ../data/MNIST_DATASET/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 8482297.73it/s]

Extracting ../data/MNIST_DATASET/MNIST/raw/train-labels-idx1-ubyte.gz to ../data/MNIST_DATASET/MNIST/raw




100%|██████████| 1648877/1648877 [00:00<00:00, 32271857.79it/s]


Extracting ../data/MNIST_DATASET/MNIST/raw/t10k-images-idx3-ubyte.gz to ../data/MNIST_DATASET/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 6940083.34it/s]


Extracting ../data/MNIST_DATASET/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../data/MNIST_DATASET/MNIST/raw



In [10]:
import torch.nn as nn
model = nn.Linear(in_features = 1, out_features = 1, bias = True)

In [11]:
class MLP(nn.Module):
  def __init__(self, inputs):
    super(MLP, self).__init__()
    self.layer = Linear(inputs, 1)
    self.activation = Sigmoid()

  def forward(self, X):
    X = self.layer(X)
    X = self.activation(X)
    return X


In [12]:
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 5),
        nn.ReLU(inplace = True),
        nn.MaxPool2d(2)
    )

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels = 64, out_channels = 30, kernel_size = 5),
        nn.ReLU(inplace = True),
        nn.MaxPool2d(2)
    )

    self.layer3 = nn.Sequential(
        nn.Linear(in_features = 30 * 5 * 5, out_features = 10, bias = True),
        nn.ReLU(inplace = True)
    )

  def forward(self, x):
    x = self.layer1(x)
    x = self.layer2(x)
    x = x.view(x.shape[0], -1)
    return x

model = MLP()

print("Printing children\n-------------------------------")
print(list(model.children()))
print("\n\nPrining Modules\n-------------------------------")
print(list(model.modules()))

Printing children
-------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Prining Modules
-------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Line

In [13]:
def MLP(in_features = 1, hidden_features = 20, out_features = -1):
  hidden = nn.Linear(in_features = in_features, out_features = hidden_features, bias = True)
  activation = nn.ReLU()
  output = nn.Linear(in_features = hidden_features, out_features = out_features, bias = True)
  net = nn.Sequential(hidden, activation, output)
  return net

In [ ]:
from torch.optim import optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr= 0.01, momentum = 0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer = optimizer, lr_lambda = lambda epoch: 0.95 ** epoch)
for epoch in range(1, 100 + 1):
  for x, y in dataloader:
    optimizer.zero_grad()
loss_fn(model(x), y).backward()
optimizer.step()
scheduler.step()

In [ ]:
for epoch in range(100):
  yhat = model(x_train)
  loss = criterion(yhat, y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [18]:
pip install torchmetrics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.4/840.4 kB 4.8 MB/s eta 0:00:00


In [20]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim = -1)
target = torch.randint(5, (10, ))

acc = torchmetrics.functional.accuracy(preds, target)

TypeError: accuracy() missing 1 required positional argument: 'task'

In [21]:
import torch
import torchmetrics
metric = torchmetrics.Accuracy()

n_batches = 10
for i in range(n_batches):
  preds = torch.randn(10, 5).softmax(dim = -1)
  target = torch.randint(5, (10, ))

  acc = metric(preds, target)
  print(f"Accuracy on batch {i} : {acc}")
acc = metric.compute()
print(f"Accuracy on all data : {acc}")

TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'

In [22]:
pip install tensorboard

In [23]:
import torch
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('../chap02/tensorboard')
for epoch in range(num_epochs):
  model.train()
  batch_loss = 0.0

  for i, (x, y) in enumerate(dataloader):
    x, y = x.to(device).float(), y.to(device).float()
    outputs = model(x)
    loss = criterion(outputs, y)
    writer.add_scaler("Loss", loss, epoch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

writer.close()

NameError: name 'num_epochs' is not defined